---
- name: install EPEL
  yum: name=epel-release state=present

- name: install tools
  yum: name={{item}} state=present
  with_items:
    - unzip

#- name: Install Firewalld
#  yum: name=firewalld state=present

#- name: Firewalld service state
#  service: name=firewalld state=started enabled=yes
