---
- name: Install NextCloud, MySQL, Nginx, and PHP-FPM
  hosts: tag_Name_lookatme
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  roles:
    - mariadb
    - nginx
    - php-fpm
    - NextCloud
