---
- name: Install nginx
  yum: name=nginx state=present

- name: template nginx John's mom
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

#- name: insert firewalld rule for nginx
#  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
#  ignore_errors: yes

- name: http service state
  service: name=nginx state=started enabled=yes
