---
- name: Download Next Cloud
  get_url: url=https://download.nextcloud.com/server/releases/nextcloud-12.0.0.zip
    dest=/tmp/

- name: extract installer
  unarchive:
    src: /tmp/nextcloud-12.0.0.zip
    dest: /usr/share/nginx/html
    remote_src: True
    owner: nginx
    group: nginx

- name: Template config file
  template:
    src: config.php
    dest: /usr/share/nginx/html/nextcloud/config/config.php
  notify: restart nginx

#- name: Add group "nextcloud"
#  group: name=nextcloud

#- name: Add user "nextcloud"
#  user: name=nextcloud group=nextcloud home=/srv/nextcloud/

- name: Create datadir
  file: dest=/opt/nextcloud/data owner=nginx group=nginx mode=0755 state=directory

- name: Create NextCloud database
  mysql_db: name={{ nc_db_name }} state=present

- name: Create NextCloud database user
  mysql_user: name={{ nc_db_user }} password={{ nc_db_password }} priv={{ nc_db_name }}.*:ALL host='localhost' state=present
